<?php
require_once '../config/db.php';
if(session_status()===PHP_SESSION_NONE)session_start();
if(!isset($_SESSION['user_id'])){header('Location: ../login.php');exit;}
$user_id=(int)$_SESSION['user_id']; if(empty($_SESSION['chat_csrf']))$_SESSION['chat_csrf']=bin2hex(random_bytes(32));$csrf=$_SESSION['chat_csrf'];
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$conversation_id=(int)($_GET['conversation_id']??0); if($conversation_id<=0){header('Location: chat_requests.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrf,(string)($_POST['csrf_token']??''))){header('Location: chat.php?conversation_id='.$conversation_id.'&message='.urlencode('Security check failed.'));exit;}
 $message=trim((string)($_POST['message']??''));
 if($message===''){header('Location: chat.php?conversation_id='.$conversation_id.'&message='.urlencode('Please write a message.'));exit;}
 if(mb_strlen($message)>1000)$message=mb_substr($message,0,1000);
 $st=mysqli_prepare($conn,"SELECT c.*,cr.status AS request_status,cr.chat_active,cr.sender_user_id AS req_sender,cr.receiver_user_id AS req_receiver FROM conversations c JOIN chat_requests cr ON cr.chat_request_id=c.chat_request_id WHERE c.conversation_id=? AND (c.user1_id=? OR c.user2_id=?) LIMIT 1");mysqli_stmt_bind_param($st,'iii',$conversation_id,$user_id,$user_id);mysqli_stmt_execute($st);$conv=mysqli_fetch_assoc(mysqli_stmt_get_result($st));mysqli_stmt_close($st);
 if(!$conv||$conv['status']!=='Active'||$conv['request_status']!=='Accepted'||(int)$conv['chat_active']!==1){header('Location: chat_requests.php?message='.urlencode('This conversation is no longer active.'));exit;}
 $count=(int)($conv['user1_id']==$user_id?$conv['user1_message_count']:$conv['user2_message_count']);$limit=(int)$conv['message_limit'];
 if($count >= $limit){header('Location: chat.php?conversation_id='.$conversation_id.'&message='.urlencode('Your message limit for this conversation has been reached.'));exit;}
 mysqli_begin_transaction($conn);try{$st=mysqli_prepare($conn,"INSERT INTO conversation_messages(conversation_id,sender_user_id,message) VALUES(?,?,?)");mysqli_stmt_bind_param($st,'iis',$conversation_id,$user_id,$message);if(!mysqli_stmt_execute($st))throw new Exception();mysqli_stmt_close($st);if((int)$conv['user1_id']===$user_id)$sql="UPDATE conversations SET user1_message_count=user1_message_count+1 WHERE conversation_id=?";else$sql="UPDATE conversations SET user2_message_count=user2_message_count+1 WHERE conversation_id=?";$st=mysqli_prepare($conn,$sql);mysqli_stmt_bind_param($st,'i',$conversation_id);if(!mysqli_stmt_execute($st))throw new Exception();mysqli_stmt_close($st);mysqli_commit($conn);}catch(Throwable $e){mysqli_rollback($conn);header('Location: chat.php?conversation_id='.$conversation_id.'&message='.urlencode('Unable to send message right now.'));exit;}header('Location: chat.php?conversation_id='.$conversation_id);exit;
}
$st=mysqli_prepare($conn,"SELECT c.*,cr.status AS request_status,cr.chat_active,CONCAT(u.first_name,' ',u.last_name) AS other_name,u.user_id AS other_id,up.photo,up.photo_visibility FROM conversations c JOIN chat_requests cr ON cr.chat_request_id=c.chat_request_id JOIN users u ON u.user_id=CASE WHEN c.user1_id=? THEN c.user2_id ELSE c.user1_id END LEFT JOIN user_profiles up ON up.user_id=u.user_id WHERE c.conversation_id=? AND (c.user1_id=? OR c.user2_id=?) LIMIT 1");mysqli_stmt_bind_param($st,'iiii',$user_id,$conversation_id,$user_id,$user_id);mysqli_stmt_execute($st);$conv=mysqli_fetch_assoc(mysqli_stmt_get_result($st));mysqli_stmt_close($st);if(!$conv){header('Location: chat_requests.php?message='.urlencode('Conversation not found.'));exit;}
$st=mysqli_prepare($conn,"SELECT cm.*,CONCAT(u.first_name,' ',u.last_name) sender_name FROM conversation_messages cm JOIN users u ON u.user_id=cm.sender_user_id WHERE cm.conversation_id=? ORDER BY cm.message_id ASC");mysqli_stmt_bind_param($st,'i',$conversation_id);mysqli_stmt_execute($st);$messages=[];$res=mysqli_stmt_get_result($st);while($m=mysqli_fetch_assoc($res))$messages[]=$m;mysqli_stmt_close($st);$flash=$_GET['message']??'';$mine=(int)$conv['user1_id']===$user_id?(int)$conv['user1_message_count']:(int)$conv['user2_message_count'];
include '../includes/header.php';include '../includes/navbar.php';
?><main class="chat-page"><div class="chat-wrap"><a class="chat-back" href="chat_requests.php"><i class="fa-solid fa-arrow-left"></i> Messages</a><section class="conversation"><header class="conversation-head"><div class="chat-avatar small"><?php if(!empty($conv['photo'])):?><img src="<?=BASE_URL?>uploads/profile/<?=h($conv['photo'])?>" alt="Profile photo"><?php else:?><i class="fa-solid fa-user"></i><?php endif;?></div><div><span>PRIVATE CONVERSATION</span><h1><?=h($conv['other_name'])?></h1><p>Respectful communication • <?=$mine?> / <?=h($conv['message_limit'])?> messages used</p></div><a href="../profile/view_profile.php?user_id=<?=h($conv['other_id'])?>" class="chat-secondary">View Profile</a></header><?php if($flash):?><div class="chat-alert info"><?=h($flash)?></div><?php endif;?><div class="message-list"><?php if(!$messages):?><div class="message-empty"><i class="fa-regular fa-message"></i><p>No messages yet. Start with a respectful introduction.</p></div><?php else:foreach($messages as $m):?><div class="bubble-row <?=$m['sender_user_id']==$user_id?'mine':'theirs'?>"><div class="bubble"><div><?=nl2br(h($m['message']))?></div><small><?=h(date('d M Y, h:i A',strtotime($m['created_at'])))?></small></div></div><?php endforeach;endif;?></div><?php if($conv['status']==='Active'&&$conv['request_status']==='Accepted'&&(int)$conv['chat_active']===1&&$mine<(int)$conv['message_limit']):?><form class="message-form" method="post"><input type="hidden" name="csrf_token" value="<?=h($csrf)?>"><textarea name="message" maxlength="1000" placeholder="Write a respectful message…" required></textarea><button class="chat-primary">Send Message <i class="fa-solid fa-paper-plane"></i></button></form><?php elseif($mine>=(int)$conv['message_limit']):?><div class="limit-note">You have reached the <?=$conv['message_limit']?>-message limit for this conversation.</div><?php else:?><div class="limit-note">This conversation is closed.</div><?php endif;?><form method="post" action="chat_action.php" class="close-chat-form"><input type="hidden" name="csrf_token" value="<?=h($csrf)?>"><input type="hidden" name="chat_request_id" value="<?=h($conv['chat_request_id'])?>"><button name="action" value="close_chat" class="chat-danger">Close Conversation</button></form></section></div></main><link rel="stylesheet" href="../assets/css/chat.css">
<script src="../assets/js/chat-menu.js"></script><script>window.addEventListener('load',function(){const el=document.querySelector('.message-list');if(el)el.scrollTop=el.scrollHeight;});</script>
