<?php
require_once '../config/db.php';
if (session_status() === PHP_SESSION_NONE) { session_name('SMART_ADMIN_SESSION'); session_start(); }
if (empty($_SESSION['admin_user_id'])) { header('Location: login.php'); exit; }
$admin_id=(int)$_SESSION['admin_user_id'];
if(empty($_SESSION['admin_csrf'])) $_SESSION['admin_csrf']=bin2hex(random_bytes(32));
$csrf=$_SESSION['admin_csrf']; $message=''; $error='';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function public_id($id){return 'SM-'.str_pad((string)(int)$id,6,'0',STR_PAD_LEFT);}
$uid=(int)($_GET['user_id']??$_POST['user_id']??0);
if($uid<=0 || $uid===$admin_id){header('Location: users.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrf,(string)($_POST['csrf']??''))){$error='Security check failed. Please refresh and try again.';}
 else{
  $action=$_POST['action']??'';
  if($action==='moderate'){
   $role=$_POST['role']??''; $account=$_POST['account_status']??''; $verification=$_POST['verification_status']??''; $profile_visibility=$_POST['profile_visibility']??''; $photo_visibility=$_POST['photo_visibility']??''; $voice_visibility=$_POST['voice_visibility']??''; $video_visibility=$_POST['video_visibility']??'';
   $roles=['User','Manager','Authenticator']; $accounts=['Active','Inactive','Suspended']; $ver=['Pending','Verified','Rejected']; $pv=['Public','Hidden']; $ph=['Everyone','Verified Users','Matched Users','Hidden']; $mv=['Everyone','Verified Users','Matched Users','Private'];
   if(!in_array($role,$roles,true)||!in_array($account,$accounts,true)||!in_array($verification,$ver,true)||!in_array($profile_visibility,$pv,true)||!in_array($photo_visibility,$ph,true)||!in_array($voice_visibility,$mv,true)||!in_array($video_visibility,$mv,true)){$error='Invalid moderation value.';}
   else{
    mysqli_begin_transaction($conn);
    try{
     $st=mysqli_prepare($conn,"UPDATE users SET role=?,account_status=? WHERE user_id=? AND role<>'Admin'"); mysqli_stmt_bind_param($st,'ssi',$role,$account,$uid); if(!mysqli_stmt_execute($st))throw new Exception(); mysqli_stmt_close($st);
     if ($user_profile_exists = !empty($_POST['has_profile'])) {
      $st=mysqli_prepare($conn,"UPDATE user_profiles SET verification_status=?,profile_visibility=?,photo_visibility=? WHERE user_id=?"); mysqli_stmt_bind_param($st,'sssi',$verification,$profile_visibility,$photo_visibility,$uid); if(!mysqli_stmt_execute($st))throw new Exception(); mysqli_stmt_close($st);

      $st=mysqli_prepare($conn,"UPDATE profile_media SET visibility=? WHERE user_id=? AND media_type='Voice Introduction' AND status='Active'");
      if(!$st) throw new Exception(); mysqli_stmt_bind_param($st,'si',$voice_visibility,$uid); if(!mysqli_stmt_execute($st))throw new Exception(); mysqli_stmt_close($st);

      $st=mysqli_prepare($conn,"UPDATE profile_media SET visibility=? WHERE user_id=? AND media_type='Video Introduction' AND status='Active'");
      if(!$st) throw new Exception(); mysqli_stmt_bind_param($st,'si',$video_visibility,$uid); if(!mysqli_stmt_execute($st))throw new Exception(); mysqli_stmt_close($st);
   }
     mysqli_commit($conn); $message=$user_profile_exists ? 'Account and profile controls updated successfully.' : 'Account controls updated successfully. This user has no profile yet.';
    }catch(Throwable $e){mysqli_rollback($conn);$error='Unable to save moderation changes.';}
   }
  }
 }
}
$stmt=mysqli_prepare($conn,"SELECT u.*,up.profile_id,up.date_of_birth,up.religion,up.madhhab,up.marital_status,up.bio,up.photo,up.height_cm,up.weight_kg,up.complexion,up.country,up.area,up.division_id,up.district_id,up.upazila_id,up.nid_number,up.post_office,up.postal_code,up.highest_education,up.profession,up.occupation_details,up.monthly_income,up.family_type,up.family_status,up.smoking_status,up.prayer_status,up.beard_status,up.hijab_status,up.verification_status,up.profile_visibility,up.photo_visibility,up.updated_at,dv.name_bn AS division_name_bn,ds.name_bn AS district_name_bn,uz.name_bn AS upazila_name_bn
FROM users u LEFT JOIN user_profiles up ON up.user_id=u.user_id LEFT JOIN divisions dv ON dv.id=up.division_id LEFT JOIN districts ds ON ds.id=up.district_id LEFT JOIN upazilas uz ON uz.id=up.upazila_id WHERE u.user_id=? AND u.role<>'Admin' LIMIT 1");
mysqli_stmt_bind_param($stmt,'i',$uid);mysqli_stmt_execute($stmt);$res=mysqli_stmt_get_result($stmt);$user=mysqli_fetch_assoc($res);mysqli_stmt_close($stmt);if(!$user){header('Location: users.php');exit;}
$age='Not informed'; if(!empty($user['date_of_birth'])){$dob=new DateTime($user['date_of_birth']);$now=new DateTime();$age=$dob->diff($now)->y.' yrs';}
$height='Not informed'; if(!empty($user['height_cm'])){$cm=(int)$user['height_cm'];$in=round($cm/2.54);$ft=intdiv($in,12);$inch=$in%12;$height=$ft.' ft '. $inch.' in';}
$location_parts=[];foreach(['area','upazila_name_bn','district_name_bn','division_name_bn'] as $f){if(!empty($user[$f]))$location_parts[]=$user[$f];}$location=$location_parts?implode(', ',$location_parts):'Not informed';
$voice_visibility='Verified Users'; $video_visibility='Verified Users';
$media_stmt=mysqli_prepare($conn,"SELECT media_type,visibility FROM profile_media WHERE user_id=? AND status='Active' AND media_type IN ('Voice Introduction','Video Introduction') ORDER BY media_id DESC");
if($media_stmt){mysqli_stmt_bind_param($media_stmt,'i',$uid);mysqli_stmt_execute($media_stmt);$media_result=mysqli_stmt_get_result($media_stmt);while($media_result && ($media_row=mysqli_fetch_assoc($media_result))){if($media_row['media_type']==='Voice Introduction' && $voice_visibility==='Verified Users') $voice_visibility=(string)$media_row['visibility']; if($media_row['media_type']==='Video Introduction' && $video_visibility==='Verified Users') $video_visibility=(string)$media_row['visibility'];}mysqli_stmt_close($media_stmt);}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>User Details | Smart Matrimony</title><link rel="stylesheet" href="../assets/css/admin.css"><link rel="stylesheet" href="../assets/css/admin-users.css"></head><body>
<header class="topbar"><div><span class="eyebrow">ACCOUNT DETAILS</span><h1><?=h($user['first_name'].' '.$user['last_name'])?></h1><p class="top-subtitle"><?=h(public_id($uid))?> · Full administrative view</p></div><div class="top-actions"><a href="users.php">← User Management</a><a href="logout.php">Logout</a></div></header>
<main class="wrap detail-wrap"><?php if($message):?><div class="admin-toast success">✓ <?=h($message)?></div><?php endif;?><?php if($error):?><div class="admin-toast error">! <?=h($error)?></div><?php endif;?>
<section class="detail-hero panel"><div class="detail-avatar"><?php if(!empty($user['photo'])):?><img src="../uploads/profile/<?=h($user['photo'])?>" alt="Profile photo"><?php else:?><span>👤</span><?php endif;?></div><div><span class="public-id large"><?=h(public_id($uid))?></span><h2><?=h($user['first_name'].' '.$user['last_name'])?></h2><p><?=h($user['gender'])?> · <?=h($user['email'])?> · <?=h($user['mobile'])?></p><div class="detail-badges"><span><?=h($user['role'])?></span><span><?=h($user['account_status'])?></span><?php if($user['profile_id']):?><span><?=h($user['verification_status'])?></span><?php endif;?></div></div></section>
<section class="panel"><div class="panel-head"><div><span class="eyebrow">ADMIN CONTROL</span><h2>Account & Profile Moderation</h2></div></div><form method="post" class="moderation-grid"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="user_id" value="<?=$uid?>"><input type="hidden" name="action" value="moderate"><input type="hidden" name="has_profile" value="<?=!empty($user['profile_id'])?1:0?>"><label>Role<select name="role"><?php foreach(['User','Manager','Authenticator'] as $r):?><option <?=$user['role']===$r?'selected':''?>><?=$r?></option><?php endforeach;?></select></label><label>Account status<select name="account_status"><?php foreach(['Active','Inactive','Suspended'] as $s):?><option <?=$user['account_status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></label><label>Verification<select name="verification_status" <?=!$user['profile_id']?'disabled':''?>><?php foreach(['Pending','Verified','Rejected'] as $v):?><option <?=$user['verification_status']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Profile visibility<select name="profile_visibility" <?=!$user['profile_id']?'disabled':''?>><?php foreach(['Public','Hidden'] as $v):?><option <?=$user['profile_visibility']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Photo visibility<select name="photo_visibility" <?=!$user['profile_id']?'disabled':''?>><?php foreach(['Everyone','Verified Users','Matched Users','Hidden'] as $v):?><option <?=$user['photo_visibility']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Voice visibility<select name="voice_visibility" <?=!$user['profile_id']?'disabled':''?>><?php foreach(['Everyone','Verified Users','Matched Users','Private'] as $v):?><option <?=$voice_visibility===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Video visibility<select name="video_visibility" <?=!$user['profile_id']?'disabled':''?>><?php foreach(['Everyone','Verified Users','Matched Users','Private'] as $v):?><option <?=$video_visibility===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><button type="submit">Save Changes</button></form></section>
<section class="detail-grid"><div class="panel"><span class="eyebrow">PROFILE INFORMATION</span><h2>Personal & Matrimony</h2><dl class="info-list"><dt>Age</dt><dd><?=h($age)?></dd><dt>Location</dt><dd><?=h($location)?></dd><dt>NID / BCN</dt><dd><?=h($user['nid_number']?:'Not informed')?></dd><dt>Religion</dt><dd><?=h($user['religion']?:'Not informed')?></dd><dt>Madhhab</dt><dd><?=h($user['madhhab']?:'Not informed')?></dd><dt>Marital status</dt><dd><?=h($user['marital_status']?:'Not informed')?></dd><dt>Education</dt><dd><?=h($user['highest_education']?:'Not informed')?></dd><dt>Profession</dt><dd><?=h($user['profession']?:'Not informed')?></dd><dt>Occupation details</dt><dd><?=h($user['occupation_details']?:'Not informed')?></dd><dt>Monthly income</dt><dd><?=!empty($user['monthly_income'])?'৳ '.number_format((float)$user['monthly_income'],2):'Not informed'?></dd><dt>Family</dt><dd><?=h($user['family_type']?:'Not informed')?> · <?=h($user['family_status']?:'Not informed')?></dd></dl></div><div class="panel"><span class="eyebrow">ACCOUNT INFORMATION</span><h2>System Data</h2><dl class="info-list"><dt>User ID</dt><dd><?=h(public_id($uid))?> (#<?=h($uid)?>)</dd><dt>Email</dt><dd><?=h($user['email'])?></dd><dt>Mobile</dt><dd><?=h($user['mobile'])?></dd><dt>Gender</dt><dd><?=h($user['gender'])?></dd><dt>Created</dt><dd><?=h(date('d M Y H:i',strtotime($user['created_at'])))?></dd><dt>Profile updated</dt><dd><?=!empty($user['updated_at'])?h(date('d M Y H:i',strtotime($user['updated_at']))):'No profile'?></dd><dt>Photo visibility</dt><dd><?=h($user['photo_visibility']?:'No profile')?></dd><dt>Voice visibility</dt><dd><?=h($voice_visibility?:'No profile')?></dd><dt>Video visibility</dt><dd><?=h($video_visibility?:'No profile')?></dd></dl></div></section>
<section class="danger-panel"><div><span class="eyebrow">DANGER ZONE</span><h2>Permanently remove account</h2><p>This permanently deletes the account and all user-owned records covered by the database cascade rules. Manager-owned packages/bookings are not deleted; their owner reference is cleared by the database.</p></div><button type="button" class="btn-danger big" id="open-delete">Remove Account Permanently</button></section>
<div class="delete-modal" id="delete-modal" aria-hidden="true"><div class="delete-card"><div class="warning-icon">!</div><h2>Permanently delete this account?</h2><p>This cannot be undone. Type <strong>DELETE</strong> to confirm.</p><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="user_id" value="<?=$uid?>"><input name="confirm_text" autocomplete="off" placeholder="Type DELETE" required><div><button type="button" class="btn-light" id="close-delete">Cancel</button><button class="btn-danger" type="submit">Yes, permanently delete</button></div></form></div></div>
</main><script>const m=document.getElementById('delete-modal');document.getElementById('open-delete').onclick=()=>{m.classList.add('show');m.setAttribute('aria-hidden','false')};document.getElementById('close-delete').onclick=()=>{m.classList.remove('show');m.setAttribute('aria-hidden','true')};m.addEventListener('click',e=>{if(e.target===m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}});</script></body></html>
